#mysql  数据库配置
server:
  port: 8082
  servlet:
    context-path: /qzznnb
spring:
  datasource:
    username: root
    password: "0000"
    url: jdbc:mysql://localhost:3306/qzznnb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
    druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000 #获取连接 等待超时时间
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 30000
        validation-query: select 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filter:
          stat:
            merge-sql: true
            slow-sql-millis: 5000
          #3.基础监控配置
        web-stat-filter:
          enabled: true
          url-pattern: /*
          #设置不统计哪些URL
          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
          session-stat-enable: true
          session-stat-max-count: 100
        stat-view-servlet:
          url-pattern: /druid/*
          reset-enable: true
          #设置监控页面的登录名和密码
          login-username: qzznnb
          login-password: qzznnb
          allow: 127.0.0.1
          #deny: 192.168.1.100
          enabled: true

  #redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200 #连接池最大连接数
        max-wait: -1 #最大阻塞等待时间
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
    timeout: 1000 #连接超时时间 毫秒
    #页面配置
  freemarker:
    suffix: .html
    #template-loader-path: classpath:/views/   #非templates目录是需要指定模板路径的，thymeleaf默认的前缀是templat

#mtbatis 配置
mybatis:
  mapper-locations:  classpath:mapping/*Mapper.xml,classpath:mapping/*/*Mapper.xml
  type-aliases-package: com.whx.qzznb.*.entity,com.whx.qzznnb.entity

#日志配置
logging:
  file: qzznnb_log/qzzns.log #绝对路径
  level:
    root: info

